# Generated by Django 4.0 on 2022-06-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_food', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('ingredients', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('resto_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='resto.resto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resto', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='RestoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_image', models.ImageField(upload_to='')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_image', to='resto.resto')),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_image', to='resto.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='resto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_type', to='resto.resto'),
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_image', to='resto.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_menu', to='resto.menu'),
        ),
        migrations.AddField(
            model_name='food',
            name='resto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resto_name_menu', to='resto.resto'),
        ),
    ]
