# Generated by Django 4.0 on 2022-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_resto_closing_time_resto_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='num_of_tables',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
