# Generated by Django 4.0 on 2022-06-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resto', '0003_resto_closing_time_resto_opening_time'),
        ('account', '0002_infouser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField()),
                ('amount_of_people', models.PositiveIntegerField(default=1)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='resto.resto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='account.user')),
            ],
        ),
    ]
