# Generated by Django 4.0 on 2022-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_of_people',
            field=models.PositiveIntegerField(),
        ),
    ]
